{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "simple-cache-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "simple-cache-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "simple-cache-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 30s
{{- end }}
