# permissions for end users to view cacheclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cachecluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: cachecluster-viewer-role
rules:
- apiGroups:
  - cache.shenle.lu
  resources:
  - cacheclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.shenle.lu
  resources:
  - cacheclusters/status
  verbs:
  - get
