mode: distributed
node_id: n3
grpc_addr: ":5053"
http_addr: ":8082"
raft_http_addr: ":9092"
metrics_addr: ":2114"
peers:
  - "http://127.0.0.1:9090"
  - "http://127.0.0.1:9091"
  - "http://127.0.0.1:9092"
heartbeat_ms: 200
election_ms: 1200
hot_reload: false
